[package]
name = "yubotp"
version = "0.1.0"
authors = [
    "Alessio Di Mauro <alessio@alessiodimauro.com>",
    "Alessandro Carlo Chirico <alessandro.carlo@chiri.co>"
]
edition = "2018"

[dependencies]
actix = "0.10.0"
actix-rt = "1.1.1"
actix-web = { version = "3.3.2", features = ["openssl"] }
base64 = "0.13.0"
bytes = "1.0.0"
config = "0.10.1"
env_logger = "0.8.2"
futures = "0.3.8"
hex = "0.4.2"
lazy_static = "1.4.0"
log = "0.4.11"
rand = "0.8.0"
regex = "1.4.2"
rust-crypto = "0.2.36"
serde = "1.0.118"
serde_derive = "1.0.118"
serde_json = "1.0.61"
tokio = "1.0.1"
