[package]
name = "yubotp"
version = "0.1.0"
authors = [
    "Alessio Di Mauro <alessio@alessiodimauro.com>",
    "Alessandro Carlo Chirico <alessandro.carlo@chiri.co>"
]
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
actix-web = { version = "3.1.0", features = ["openssl"] }
base64 = "0.13.0"
bytes = "0.5.6"
config = "0.10.1"
env_logger = "0.7.1"
futures = "0.3.5"
hex = "0.4.2"
lazy_static = "1.4.0"
log = "0.4.11"
rand = "0.7.3"
regex = "1.3.9"
rust-crypto = "0.2.36"
serde = "1.0.116"
serde_derive = "1.0.116"
serde_json = "1.0.58"
tokio = "0.2.22"
