[package]
name = "yubotp"
version = "0.1.0"
authors = [
    "Alessio Di Mauro <alessio@alessiodimauro.com>",
    "Alessandro Carlo Chirico <alessandro.carlo@chiri.co>"
]
edition = "2018"

[dependencies]
actix-rt = "1.0.0"
actix-web = { version = "2.0.0", features = ["openssl"] }
base64 = "0.11.0"
bytes = "0.5.3"
config = "0.10.1"
env_logger = "0.7.1"
futures = "0.3.1"
futures-util = "0.3.1"
hex = "0.4.0"
lazy_static = "1.4.0"
log = "0.4.8"
rand = "0.7.2"
regex = "1.3.1"
rust-crypto = "0.2.36"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
