[package]
name = "yubotp"
version = "0.1.0"
authors = [
    "Alessio Di Mauro <alessio@alessiodimauro.com>",
    "Alessandro Carlo Chirico <alessandro.carlo@chiri.co>"
]
edition = "2018"

[dependencies]
base64 = "0.10.0"
config = "0.9.1"
env_logger = "0.5.13"
hex = "0.3.2"
lazy_static = "1.1.0"
log = "0.4.5"
rand = "0.5.5"
regex = "1.0.5"
rust-crypto = "0.2.36"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
futures = "0.1.25"
bytes = "0.4.10"


[dependencies.actix-web]
version = "0.7.13"
features = ["tls"]
