#[server]
#address = "0.0.0.0"
#port = 8080

[slack]
bottoken = ""
signingsecret = ""

# [otpvalidation]
# apihost = "xxxx"
# apikey = "yyyy"
# clientid = "1234"

[answers]
newdevice = [
  "Welcome!",
  "Enjoy your new device",
  "It's a rite of passage",
]

success = [
  "You're cool $u",
  "You know you can disable carriage return, right?",
  "Did you know that you can have OTPs in slot 2 with a long touch?",
  "Ccccccongratulations!",
  "Access not granted, please use the Blue Key",
  "Fine... I'll validate that for you... Done!",
  "Yup, the Yubicloud is still up, thanks for checking",
  "Don't worry $u, I won't tell anybody that you accidentally touched your YubiKey"
]

replayed = [
  "It's an OTP alright, but somebody validated that before me",
  "I've seen that before",
  "Revenge of the OTP",
  "The \"OT\" stands for \"One Time\""
]

deleted = [
  "Hey you deleted your message! That's not fair!",
  "I was sure I saw a message with an OTP...",
  "Wait! Where did that message go!?",
  "Am I seeing OTPs that aren't there? Help!",
  "I was faster than you!",
  "Deleting the message is cheating",
  "I must have imagined it",
  "I must be tired"
]

[explanation]
success = "_The OTP has been consumed._"
replayed = "_Replayed OTP, it has already been consumed._"

# [counterthresholds]
# ctr = 0
# usage = 0
